import type { SpotPreset } from "@/lib/types";

// Starter presets only. The UI labels orientation as editable because every beach bend differs.
export const SPOT_PRESETS: SpotPreset[] = [
  {
    id: "nabeul",
    name: "نابل",
    governorate: "نابل",
    latitude: 36.4561,
    longitude: 10.7389,
    orientation: 90,
    shoreType: "sandy",
    note: "اتجاه أولي — عدّله حسب الجزء الذي تقف فيه",
  },
  {
    id: "kelibia",
    name: "المنصورة — قليبية",
    governorate: "نابل",
    latitude: 36.8368,
    longitude: 11.1197,
    orientation: 60,
    shoreType: "sandy",
    note: "خليط رمل وصخر حسب الجزء",
  },
  {
    id: "rafraf",
    name: "رفراف",
    governorate: "بنزرت",
    latitude: 37.1908,
    longitude: 10.1835,
    orientation: 35,
    shoreType: "sandy",
    note: "الاتجاه يتبدل داخل الخليج",
  },
  {
    id: "tabarka",
    name: "طبرقة",
    governorate: "جندوبة",
    latitude: 36.9544,
    longitude: 8.7581,
    orientation: 330,
    shoreType: "rocky",
    note: "اختر نوع الوقوف بدقة قبل القرار",
  },
  {
    id: "mahdia",
    name: "المهدية",
    governorate: "المهدية",
    latitude: 35.5047,
    longitude: 11.0622,
    orientation: 75,
    shoreType: "sandy",
    note: "اتجاه أولي للساحل الشرقي",
  },
  {
    id: "sfax",
    name: "سيدي منصور — صفاقس",
    governorate: "صفاقس",
    latitude: 34.799,
    longitude: 10.856,
    orientation: 85,
    shoreType: "sandy",
    note: "منطقة ضحلة ومدّها مؤثر؛ عاين الوصول",
  },
  {
    id: "gabes",
    name: "قابس",
    governorate: "قابس",
    latitude: 33.899,
    longitude: 10.119,
    orientation: 70,
    shoreType: "sandy",
    note: "خليج قابس: لا تتجاهل تغير مستوى البحر",
  },
  {
    id: "djerba",
    name: "أغير — جربة",
    governorate: "مدنين",
    latitude: 33.768,
    longitude: 11.012,
    orientation: 85,
    shoreType: "sandy",
    note: "اتجاه أولي للساحل الشرقي للجزيرة",
  },
  {
    id: "zarzis",
    name: "جرجيس",
    governorate: "مدنين",
    latitude: 33.507,
    longitude: 11.112,
    orientation: 90,
    shoreType: "sandy",
    note: "اتجاه أولي — ثبّت موقعك على الخريطة",
  },
  {
    id: "bizerte",
    name: "بنزرت — شاطئ المدينة",
    governorate: "بنزرت",
    latitude: 37.276,
    longitude: 9.872,
    orientation: 0,
    shoreType: "sandy",
    note: "اتجاه أولي تقريبي — عدّله حسب الجزء الذي تقف فيه",
  },
  {
    id: "ghar-el-melh",
    name: "غار الملح",
    governorate: "بنزرت",
    latitude: 37.169,
    longitude: 10.192,
    orientation: 30,
    shoreType: "sandy",
    note: "خليج ضحل وقرب مصب مجردة — عاين التيار",
  },
  {
    id: "gammarth",
    name: "قمرت — المرسى",
    governorate: "تونس",
    latitude: 36.912,
    longitude: 10.306,
    orientation: 45,
    shoreType: "sandy",
    note: "ساحل خليج تونس الشمالي — اتجاه أولي تقريبي",
  },
  {
    id: "la-goulette",
    name: "حلق الوادي",
    governorate: "تونس",
    latitude: 36.818,
    longitude: 10.306,
    orientation: 70,
    shoreType: "jetty",
    note: "رصيف وحواجز — قرب الميناء انتبه للمناطق الممنوعة",
  },
  {
    id: "haouaria",
    name: "الهوارية",
    governorate: "نابل",
    latitude: 37.056,
    longitude: 11.015,
    orientation: 0,
    shoreType: "rocky",
    note: "رأس صخري شمال الوطن القبلي — صخور مغمورة",
  },
  {
    id: "korba",
    name: "قربة",
    governorate: "نابل",
    latitude: 36.578,
    longitude: 10.857,
    orientation: 90,
    shoreType: "sandy",
    note: "اتجاه أولي تقريبي للساحل الشرقي",
  },
  {
    id: "beni-khiar",
    name: "بني خيار",
    governorate: "نابل",
    latitude: 36.469,
    longitude: 10.781,
    orientation: 90,
    shoreType: "sandy",
    note: "اتجاه أولي تقريبي — ثبّت الجزء على الخريطة",
  },
  {
    id: "hammamet",
    name: "الحمامات",
    governorate: "نابل",
    latitude: 36.400,
    longitude: 10.617,
    orientation: 85,
    shoreType: "sandy",
    note: "خليج الحمامات — الاتجاه يتبدل داخل الخليج",
  },
  {
    id: "sousse",
    name: "سوسة",
    governorate: "سوسة",
    latitude: 35.825,
    longitude: 10.638,
    orientation: 90,
    shoreType: "sandy",
    note: "ساحل رملي مفتوح — عاين الكسرة قبل النصب",
  },
  {
    id: "monastir",
    name: "المنستير",
    governorate: "المنستير",
    latitude: 35.763,
    longitude: 10.826,
    orientation: 90,
    shoreType: "rocky",
    note: "خليط رمل وصخر — اختر نوع الوقوف بدقة",
  },
  {
    id: "chebba",
    name: "الشابة",
    governorate: "المهدية",
    latitude: 35.239,
    longitude: 11.114,
    orientation: 90,
    shoreType: "sandy",
    note: "قرب حدود خليج قابس — المدّ بدأ يقوى",
  },
  {
    id: "ben-guerdane",
    name: "بن قردان",
    governorate: "مدنين",
    latitude: 33.138,
    longitude: 11.216,
    orientation: 90,
    shoreType: "sandy",
    note: "أقصى الجنوب الشرقي — اتجاه أولي تقريبي",
  },
];
