import type { SpotPreset } from "@/lib/types";

// Starter presets identify place names and coordinates only; all coastal properties are fetched per selected point.
export const SPOT_PRESETS: SpotPreset[] = [
  {
    id: "nabeul",
    name: "نابل",
    governorate: "نابل",
    latitude: 36.4561,
    longitude: 10.7389,
  },
  {
    id: "kelibia",
    name: "المنصورة — قليبية",
    governorate: "نابل",
    latitude: 36.8368,
    longitude: 11.1197,
  },
  {
    id: "rafraf",
    name: "رفراف",
    governorate: "بنزرت",
    latitude: 37.1908,
    longitude: 10.1835,
  },
  {
    id: "tabarka",
    name: "طبرقة",
    governorate: "جندوبة",
    latitude: 36.9544,
    longitude: 8.7581,
  },
  {
    id: "mahdia",
    name: "المهدية",
    governorate: "المهدية",
    latitude: 35.5047,
    longitude: 11.0622,
  },
  {
    id: "sfax",
    name: "سيدي منصور — صفاقس",
    governorate: "صفاقس",
    latitude: 34.799,
    longitude: 10.856,
  },
  {
    id: "gabes",
    name: "قابس",
    governorate: "قابس",
    latitude: 33.899,
    longitude: 10.119,
  },
  {
    id: "djerba",
    name: "أغير — جربة",
    governorate: "مدنين",
    latitude: 33.768,
    longitude: 11.012,
  },
  {
    id: "zarzis",
    name: "جرجيس",
    governorate: "مدنين",
    latitude: 33.507,
    longitude: 11.112,
  },
  {
    id: "bizerte",
    name: "بنزرت — شاطئ المدينة",
    governorate: "بنزرت",
    latitude: 37.276,
    longitude: 9.872,
  },
  {
    id: "ghar-el-melh",
    name: "غار الملح",
    governorate: "بنزرت",
    latitude: 37.169,
    longitude: 10.192,
  },
  {
    id: "gammarth",
    name: "قمرت — المرسى",
    governorate: "تونس",
    latitude: 36.912,
    longitude: 10.306,
  },
  {
    id: "la-goulette",
    name: "حلق الوادي",
    governorate: "تونس",
    latitude: 36.818,
    longitude: 10.306,
  },
  {
    id: "haouaria",
    name: "الهوارية",
    governorate: "نابل",
    latitude: 37.056,
    longitude: 11.015,
  },
  {
    id: "korba",
    name: "قربة",
    governorate: "نابل",
    latitude: 36.578,
    longitude: 10.857,
  },
  {
    id: "beni-khiar",
    name: "بني خيار",
    governorate: "نابل",
    latitude: 36.469,
    longitude: 10.781,
  },
  {
    id: "hammamet",
    name: "الحمامات",
    governorate: "نابل",
    latitude: 36.400,
    longitude: 10.617,
  },
  {
    id: "sousse",
    name: "سوسة",
    governorate: "سوسة",
    latitude: 35.825,
    longitude: 10.638,
  },
  {
    id: "monastir",
    name: "المنستير",
    governorate: "المنستير",
    latitude: 35.763,
    longitude: 10.826,
  },
  {
    id: "chebba",
    name: "الشابة",
    governorate: "المهدية",
    latitude: 35.239,
    longitude: 11.114,
  },
  {
    id: "ben-guerdane",
    name: "بن قردان",
    governorate: "مدنين",
    latitude: 33.138,
    longitude: 11.216,
  },
];
